In [1]:
from core.agent import create_agent, run_agent_with_metrics
from core.metrics import run_slow_agent
from core.report import generate_drift_report
from core.trace import init_langsmith, run_agent_with_trace

# --- Create and Compile Agent ---
agent = create_agent()

# --- Queries ---
queries = [
    "Who was the founder of SpaceX?",
    "Calculate 23 * 17",
    "When was the first iPhone released?",
    "Find population of France",
    "Calculate the area of a circle with radius 5"
]

/opt/anaconda3/envs/agents/lib/python3.12/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/Users/sam/Desktop/VScode/LLM/AAI/AgenticAI-2025/Week16/LangChain_Tool_Agent_Performance_Monitoring/core/agent.py:12: LangChainDeprecationWarning: The class `HuggingFacePipeline` was deprecated in LangChain 0.0.37 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFacePipeline``.
  llm = HuggingFacePipeline(pipeline=_hf_pipe)

## Reference Baseline Run

In [2]:
ref_metrics = run_agent_with_metrics(agent, queries)

{"timestamp": "2026-03-01 08:53:19,097", "level": "INFO", "message": "Agent Step: tool_wikipedia", "request_id": "43097a71-16ce-4e8a-b630-7b64b14757e5", "path_selected": "tool_wikipedia", "latency_sec": 5.674912000002223, "query": "who was the founder of spacex?"}

Python REPL can execute arbitrary code. Use with caution.

{"timestamp": "2026-03-01 08:53:19,200", "level": "INFO", "message": "Agent Step: tool_calculator", "request_id": "900a5175-2049-436d-960d-d970ee896767", "path_selected": "tool_calculator", "latency_sec": 0.07668658400507411, "query": "calculate 23 * 17"}
{"timestamp": "2026-03-01 08:53:23,964", "level": "INFO", "message": "Agent Step: tool_wikipedia", "request_id": "32bcaa6c-b8b2-45da-b3fa-b22f6a576089", "path_selected": "tool_wikipedia", "latency_sec": 4.7573142500041286, "query": "when was the first iphone released?"}

/opt/anaconda3/envs/agents/lib/python3.12/site-packages/transformers/generation/utils.py:1178: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

{"timestamp": "2026-03-01 08:53:24,484", "level": "INFO", "message": "Agent Step: direct_llm", "request_id": "45cf8ca4-31cf-4b54-a458-6766ca46f26b", "path_selected": "direct_llm", "latency_sec": 0.5111047090031207, "query": "find population of france"}
{"timestamp": "2026-03-01 08:53:24,492", "level": "INFO", "message": "Agent Step: tool_calculator", "request_id": "d9bc4b15-cf28-41a8-beae-207ccdc6b1f8", "path_selected": "tool_calculator", "latency_sec": 0.0028215420024935156, "query": "calculate the area of a circle with radius 5"}

In [3]:
ref_metrics

,query,response,latency,token_count,path,request_id
0,Who was the founder of SpaceX?,Page: Founders Fund\nSummary: Founders Fund is...,7.228933,574,tool_wikipedia,43097a71-16ce-4e8a-b630-7b64b14757e5
1,Calculate 23 * 17,391,0.087857,1,tool_calculator,900a5175-2049-436d-960d-d970ee896767
2,When was the first iPhone released?,Page: IPhone (1st generation)\nSummary: The iP...,4.763646,515,tool_wikipedia,32bcaa6c-b8b2-45da-b3fa-b22f6a576089
3,Find population of France,population of france,0.517181,3,direct_llm,45cf8ca4-31cf-4b54-a458-6766ca46f26b
4,Calculate the area of a circle with radius 5,SyntaxError('invalid syntax. Perhaps you forgo...,0.006197,20,tool_calculator,d9bc4b15-cf28-41a8-beae-207ccdc6b1f8

In [4]:
cur_metrics = run_slow_agent(agent, queries)

{"timestamp": "2026-03-01 08:55:58,645", "level": "INFO", "message": "Agent Step: tool_wikipedia", "request_id": "c83a1fb4-5cb6-4af0-934d-b591bfca4766", "path_selected": "tool_wikipedia", "latency_sec": 4.037583208002616, "query": "who was the founder of spacex?"}
{"timestamp": "2026-03-01 08:55:59,679", "level": "INFO", "message": "Agent Step: tool_calculator", "request_id": "1705da2b-caed-4bb0-83df-2a11f1945d30", "path_selected": "tool_calculator", "latency_sec": 0.015277375001460314, "query": "calculate 23 * 17"}
{"timestamp": "2026-03-01 08:56:04,523", "level": "INFO", "message": "Agent Step: tool_wikipedia", "request_id": "0770cb67-0e8c-4cb0-ad92-9dea29dc57f0", "path_selected": "tool_wikipedia", "latency_sec": 3.829144458002702, "query": "when was the first iphone released?"}

/opt/anaconda3/envs/agents/lib/python3.12/site-packages/transformers/generation/utils.py:1178: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

{"timestamp": "2026-03-01 08:56:06,029", "level": "INFO", "message": "Agent Step: direct_llm", "request_id": "4d5b8b2d-21fc-407a-93d7-a4f59bce8301", "path_selected": "direct_llm", "latency_sec": 0.4917070829978911, "query": "find population of france"}
{"timestamp": "2026-03-01 08:56:07,047", "level": "INFO", "message": "Agent Step: tool_calculator", "request_id": "7cef1863-c937-4853-a838-0bccc8d3620f", "path_selected": "tool_calculator", "latency_sec": 0.005011500004911795, "query": "calculate the area of a circle with radius 5"}

In [5]:
cur_metrics

,query,response,latency,token_count,path,request_id
0,Who was the founder of SpaceX?,Page: Founders Fund\nSummary: Founders Fund is...,5.072857,574,tool_wikipedia,c83a1fb4-5cb6-4af0-934d-b591bfca4766
1,Calculate 23 * 17,391,1.031302,1,tool_calculator,1705da2b-caed-4bb0-83df-2a11f1945d30
2,When was the first iPhone released?,Page: IPhone (1st generation)\nSummary: The iP...,4.843425,515,tool_wikipedia,0770cb67-0e8c-4cb0-ad92-9dea29dc57f0
3,Find population of France,population of france,1.506178,3,direct_llm,4d5b8b2d-21fc-407a-93d7-a4f59bce8301
4,Calculate the area of a circle with radius 5,SyntaxError('invalid syntax. Perhaps you forgo...,1.015966,20,tool_calculator,7cef1863-c937-4853-a838-0bccc8d3620f

In [ ]:
report = generate_drift_report(ref_metrics, cur_metrics)

[WARNING] Evidently Drift Analysis failed: No module named 'evidently'
⚠️ Generated fallback report at: /Users/sam/Desktop/VScode/LLM/AAI/AgenticAI-2025/Week16/LangChain_Tool_Agent_Performance_Monitoring/reports/drift_report.html

In [11]:
#!pip install evidently

In [10]:
report = generate_drift_report(ref_metrics, cur_metrics)

[WARNING] Evidently Drift Analysis failed: No module named 'evidently.report'
⚠️ Generated fallback report at: /Users/sam/Desktop/VScode/LLM/AAI/AgenticAI-2025/Week16/LangChain_Tool_Agent_Performance_Monitoring/reports/drift_report.html